---
- hosts: all
  connection: local

  vars_files:
    - group_vars/all
    - group_vars/secrets

  roles:
    - common
    - aws
    - docker
    - kubernetes
    - java
    - clojure
    - postgres
    - redis
    - postman
    - gpg
    - pass
    - node
